# Generated by Django 3.2.5 on 2021-07-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_api', '0002_auto_20210726_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='name',
            new_name='meal_name',
        ),
    ]
